version: '3'

services:

  app: 

    build: .
    volumes:
      - ./app:/app/app
      - ./.env:/app/.env:ro
    ports:
      - 8080:8000

networks:
  default:
    name: nginx-bridge
    external: yes