version: '3'

services:

  weather-need: 

    build: .
    volumes:
      - ./app:/app/app
      - ./.env:/app/.env:ro
    expose:
      - 8000

networks:
  default:
    name: nginx-bridge
    external: yes